CREATE TABLE profile_decorations (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    decoration_key VARCHAR(100) NOT NULL UNIQUE,
    label VARCHAR(100) NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    required_role VARCHAR(50) NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
);
