ALTER TABLE problems ADD COLUMN url VARCHAR(255);
ALTER TABLE problems MODIFY COLUMN time_limit DOUBLE NOT NULL;
ALTER TABLE problems MODIFY COLUMN memory_limit INTEGER NOT NULL;
ALTER TABLE problems MODIFY COLUMN points INTEGER NOT NULL;
ALTER TABLE problems MODIFY COLUMN is_public BIT(1) NOT NULL;
ALTER TABLE problems ADD COLUMN reference_url VARCHAR(255);