# src/test/resources/application-test.yml 수정 시 꼭 말하기
cloud:
  aws:
    credentials:
      
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false

spring:
  # ... 기존 설정들 ...
  mail:
    host: localhost
    port: 25
    username: {MAIL_USERNAME}
    password: {MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false